<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Karakol.Domain\Karakol.Domain.csproj" />
    <ProjectReference Include="..\Karakol.Parsing\Karakol.Parsing.csproj" />
    <ProjectReference Include="..\Karakol.Shared\Karakol.Shared.csproj" />
    <ProjectReference Include="..\Karakol.Application\Karakol.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
