<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Karakol.Domain\Karakol.Domain.csproj" />
    <ProjectReference Include="..\Karakol.Persistence\Karakol.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" />
  </ItemGroup>

</Project>
